version: 2
jobs:
  build:
    working_directory: ~/bin

    docker:
      - image: debian:buster

    steps:

      - run:
          name: Installing dependencies
          command: apt update && apt upgrade && apt install -y jq git openssh-client

      - checkout

      - run:
          name: Prerequisites
          command: touch ~/bin/dark-lie_ip.token && touch ~/bin/dark-lie_ds.token

      - run:
          name: Display Bash version
          command: bash --version

      - run:
          name: Run dark-lie
          command: bash dark-lie