version: 2
jobs:
  build:
    working_directory: ~/bin

    docker:
      - image: debian:buster

    steps:

      - run:
          name: Installing dependencies
          command: apt install -y jq logger git ssh

      - checkout

      - run:
          name: Run dark-lie
          command: bash dark-lie