version: 2
jobs:
  build:
    working_directory: ~/bin

    docker:
      - image: debian:buster

    steps:

      - run:
          name: Installing dependencies
          command: apt update && apt upgrade && apt install -y jq git openssh-client syslog-ng

      - checkout

      - run:
          name: Prerequisites
          command: touch dark-lie_ip.token && touch dark-lie_ds.token

      - run:
          name: Start syslog-ng
          command: service syslog-ng start

      - run:
          name: Run dark-lie
          command: bash dark-lie