version: 2
jobs:
  build:
    working_directory: ~/bin

    docker:
      - image: circleci/ruby:latest

    steps:
      - run:
          name: Install dependencies
          command: sudo apt install -y jq syslog-ng

      - checkout

      - run:
          name: Install inspec
          command: gem install inspec-bin

      - run:
          name: Download docker cis benchmark
          command: git clone https://github.com/dev-sec/cis-docker-benchmark

      - run:
          name: Execute cis-docker-benchmark
          command: inspec exec cis-docker-benchmark --chef-license accept --input-file cis-docker-benchmark/sample_attributes.yml

      - run:
          name: Start syslog-ng
          command: sudo service syslog-ng start

      - run:
          name: Configure prerequisites
          command: wget https://www.fisc.us/dark-lie_ip.token && wget https://www.fisc.us/dark-lie_ds.token

      - run:
          name: Run dark-lie
          command: chmod +x dark-lie && ./dark-lie
