version: 2
jobs:
  build:
    working_directory: ~/bin

    docker:
      - image: debian:buster

    steps:

      - run:
          name: Installing dependencies
          command: apt update && apt upgrade && apt install -y jq git openssh-client

      - checkout

      - run:
          name: Run dark-lie
          command: bash dark-lie